spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: '1234'
    url: jdbc:mysql://localhost:3306/spring_data_lab_db?allowPublicKeyRetrieval=true
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format-sql:true
server:
  port : 8090