spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: '1234'
    url: jdbc:mysql://localhost:3306/mobilelele?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
server:
  port : 8088